### ISSUE TITLE
Option to start with no preset tags

### ISSUE THREAD

**Issue by marksyzm** [ackwell/bboxed#3]
I'm looking to implement this but not all the functionality you've put in is ideal in all the tags.
Would it be possible to manually create mine instead and not have the forced `require('./tags')` part?
I can go ahead and put some work into this myself if this is too much to ask.

**Comment by ackwell** [comment]
I've added an option, `noDefaultTags`, which will stop it from using its default tags.

Hope that works for you!

(341825b1c761466d9afdaa07fddb14b7150a0f2d)

**Comment by marksyzm** [comment]
Oh brilliant! Thanks very much.

**Comment by marksyzm** [comment]
@ackwell I might do a fork and chuck in a couple more things, because I'm actually writing forum software at the moment and this is the current better package out there from what I've seen!

The first one is that if you were to use this in a browser, the tags would still be `require`d in the code which leaves unnecessary code in a bundle. We need either some sort of way to chuck an if statement around the require (which doesn't really work for browserify or webpack as they build via string replace) or we separate out the tags as an optional library that can be separately required. What do you think?

The other one is that typically with vBulletin and some other forums software, they use [list] tags that default to just using the word `[list]` for an unordered list, and you have the immediate tag value as either `[list=1]` or `[list=a] for an ordered numeric or alphabetical list. Do you want me to look into this one or do you think you could do that quickly yourself?

**Comment by ackwell** [comment]
Admittedly, the codebase was (despite intentions) never really optimised for browser-side usage - it's primary intended usage doesn't even support some of the tags it does have, so I never really got around to it. That said, I'm absolutely open to working on it a bit more.

The idea of splitting tags into a separate package is quite a good one, though the only issue I see it raising is potential backwards compatibility. I suppose it'd be easy enough to throw it out as v1 as per semantic versioning to indicate the API change.

And as for the list, it should be more than possible. I'll throw it in the issues as a to-do. I unfortunately won't have the time to really get into the codebase to make the required changes for a few days. Not sure what sort of schedule you're on, so if you're going to be implementing it, bung a message on the PR and I'll hold off.
